name: Update model definitions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC

jobs:
  run-script-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Script to Generate JSON
        run: |
          # Assuming the script is in the repository
          chmod +x ./infra/scripts/get-models.sh
          . infra/scripts/get-models.sh > ./infra/models.json

      - name: Commit JSON File
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if ! git diff --quiet ./infra/models.json; then
            git add ./infra/models.json
            git commit -m "Update JSON file from weekly script"
            git push
          else
            echo "No changes to commit"
          fi